# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'scaffoldfitterwidget.ui'
#
# Created: Tue Jun  4 13:26:03 2019
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_ScaffoldfitterWidget(object):
    def setupUi(self, shared_open_gl_widget, ScaffoldfitterWidget):
        ScaffoldfitterWidget.setObjectName("ScaffoldfitterWidget")
        ScaffoldfitterWidget.resize(1652, 998)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ScaffoldfitterWidget.sizePolicy().hasHeightForWidth())
        ScaffoldfitterWidget.setSizePolicy(sizePolicy)
        self.horizontalLayout = QtGui.QHBoxLayout(ScaffoldfitterWidget)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.dock_widget = QtGui.QDockWidget(ScaffoldfitterWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dock_widget.sizePolicy().hasHeightForWidth())
        self.dock_widget.setSizePolicy(sizePolicy)
        self.dock_widget.setMinimumSize(QtCore.QSize(346, 135))
        self.dock_widget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable | QtGui.QDockWidget.DockWidgetMovable)
        self.dock_widget.setAllowedAreas(QtCore.Qt.AllDockWidgetAreas)
        self.dock_widget.setObjectName("dockWidget")
        self.dockWidgetContents = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidgetContents.sizePolicy().hasHeightForWidth())
        self.dockWidgetContents.setSizePolicy(sizePolicy)
        self.dockWidgetContents.setObjectName("dockWidgetContents")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.dockWidgetContents)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea = QtGui.QScrollArea(self.dockWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 344, 974))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setContentsMargins(2, 2, 2, 2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.toolBox = QtGui.QToolBox(self.scrollAreaWidgetContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setStyleSheet("QToolBox::tab {\n"
"         background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                     stop: 0 #E1E1E1, stop: 0.4 #DDDDDD,\n"
"                                     stop: 0.5 #D8D8D8, stop: 1.0 #D3D3D3);\n"
"         border-radius: 5px;\n"
"         color: black;\n"
"     }\n"
"\n"
"     QToolBox::tab:selected { /* italicize selected tabs */\n"
"         font: bold;\n"
"         color: black;\n"
"     }\n"
"QToolBox {\n"
"    padding : 0\n"
"}")
        self.toolBox.setObjectName("toolBox")
        self.Scaffoldpage = QtGui.QWidget()
        self.Scaffoldpage.setGeometry(QtCore.QRect(0, 0, 340, 856))
        self.Scaffoldpage.setObjectName("Scaffoldpage")
        self.scrollArea_2 = QtGui.QScrollArea(self.Scaffoldpage)
        self.scrollArea_2.setGeometry(QtCore.QRect(10, 10, 321, 481))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea_2.sizePolicy().hasHeightForWidth())
        self.scrollArea_2.setSizePolicy(sizePolicy)
        self.scrollArea_2.setMinimumSize(QtCore.QSize(0, 0))
        self.scrollArea_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 319, 479))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollAreaWidgetContents_2.sizePolicy().hasHeightForWidth())
        self.scrollAreaWidgetContents_2.setSizePolicy(sizePolicy)
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.scaffoldFrame = QtGui.QFrame(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scaffoldFrame.sizePolicy().hasHeightForWidth())
        self.scaffoldFrame.setSizePolicy(sizePolicy)
        self.scaffoldFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.scaffoldFrame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.scaffoldFrame.setFrameShadow(QtGui.QFrame.Raised)
        self.scaffoldFrame.setObjectName("scaffoldFrame")
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.scaffoldFrame)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.subscaffold_frame = QtGui.QFrame(self.scaffoldFrame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.subscaffold_frame.sizePolicy().hasHeightForWidth())
        self.subscaffold_frame.setSizePolicy(sizePolicy)
        self.subscaffold_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.subscaffold_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.subscaffold_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.subscaffold_frame.setObjectName("subscaffold_frame")
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.subscaffold_frame)
        self.verticalLayout_15.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.verticalLayout_14.addWidget(self.subscaffold_frame)
        self.meshType_frame = QtGui.QFrame(self.scaffoldFrame)
        self.meshType_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.meshType_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.meshType_frame.setObjectName("meshType_frame")
        self.formLayout_4 = QtGui.QFormLayout(self.meshType_frame)
        self.formLayout_4.setContentsMargins(0, -1, 0, -1)
        self.formLayout_4.setObjectName("formLayout_4")
        self.meshType_label = QtGui.QLabel(self.meshType_frame)
        self.meshType_label.setObjectName("meshType_label")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.meshType_label)
        self.meshType_comboBox = QtGui.QComboBox(self.meshType_frame)
        self.meshType_comboBox.setObjectName("meshType_comboBox")
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.meshType_comboBox)
        self.parameterSet_label = QtGui.QLabel(self.meshType_frame)
        self.parameterSet_label.setObjectName("parameterSet_label")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.parameterSet_label)
        self.parameterSet_comboBox = QtGui.QComboBox(self.meshType_frame)
        self.parameterSet_comboBox.setObjectName("parameterSet_comboBox")
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.parameterSet_comboBox)
        self.verticalLayout_14.addWidget(self.meshType_frame)
        self.scaffoldFrame_line_1 = QtGui.QFrame(self.scaffoldFrame)
        self.scaffoldFrame_line_1.setFrameShape(QtGui.QFrame.HLine)
        self.scaffoldFrame_line_1.setFrameShadow(QtGui.QFrame.Sunken)
        self.scaffoldFrame_line_1.setObjectName("scaffoldFrame_line_1")
        self.verticalLayout_14.addWidget(self.scaffoldFrame_line_1)
        self.meshTypeOptions_frame = QtGui.QFrame(self.scaffoldFrame)
        self.meshTypeOptions_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.meshTypeOptions_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.meshTypeOptions_frame.setObjectName("meshTypeOptions_frame")
        self.verticalLayout_16 = QtGui.QVBoxLayout(self.meshTypeOptions_frame)
        self.verticalLayout_16.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.verticalLayout_14.addWidget(self.meshTypeOptions_frame)
        self.scaffoldFrame_line_2 = QtGui.QFrame(self.scaffoldFrame)
        self.scaffoldFrame_line_2.setFrameShape(QtGui.QFrame.HLine)
        self.scaffoldFrame_line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.scaffoldFrame_line_2.setObjectName("scaffoldFrame_line_2")
        self.verticalLayout_14.addWidget(self.scaffoldFrame_line_2)
        self.modifyOptions_frame = QtGui.QFrame(self.scaffoldFrame)
        self.modifyOptions_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.modifyOptions_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.modifyOptions_frame.setObjectName("modifyOptions_frame")
        self.verticalLayout_17 = QtGui.QVBoxLayout(self.modifyOptions_frame)
        self.verticalLayout_17.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.deleteElementRanges_label = QtGui.QLabel(self.modifyOptions_frame)
        self.deleteElementRanges_label.setObjectName("deleteElementRanges_label")
        self.verticalLayout_17.addWidget(self.deleteElementRanges_label)
        self.deleteElementsRanges_lineEdit = QtGui.QLineEdit(self.modifyOptions_frame)
        self.deleteElementsRanges_lineEdit.setObjectName("deleteElementsRanges_lineEdit")
        self.verticalLayout_17.addWidget(self.deleteElementsRanges_lineEdit)
        self.scale_label = QtGui.QLabel(self.modifyOptions_frame)
        self.scale_label.setObjectName("scale_label")
        self.verticalLayout_17.addWidget(self.scale_label)
        self.scale_lineEdit = QtGui.QLineEdit(self.modifyOptions_frame)
        self.scale_lineEdit.setObjectName("scale_lineEdit")
        self.verticalLayout_17.addWidget(self.scale_lineEdit)
        self.verticalLayout_14.addWidget(self.modifyOptions_frame)
        self.verticalLayout.addWidget(self.scaffoldFrame)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.verticalLayout_8.addLayout(self.verticalLayout)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.displayOptions_groupBox = QtGui.QGroupBox(self.Scaffoldpage)
        self.displayOptions_groupBox.setGeometry(QtCore.QRect(0, 500, 331, 195))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayOptions_groupBox.sizePolicy().hasHeightForWidth())
        self.displayOptions_groupBox.setSizePolicy(sizePolicy)
        self.displayOptions_groupBox.setObjectName("displayOptions_groupBox")
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.displayOptions_groupBox)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.displayNodes_frame = QtGui.QFrame(self.displayOptions_groupBox)
        self.displayNodes_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayNodes_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayNodes_frame.setObjectName("displayNodes_frame")
        self.horizontalLayout_6 = QtGui.QHBoxLayout(self.displayNodes_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.displayNodePoints_checkBox = QtGui.QCheckBox(self.displayNodes_frame)
        self.displayNodePoints_checkBox.setObjectName("displayNodePoints_checkBox")
        self.horizontalLayout_6.addWidget(self.displayNodePoints_checkBox)
        self.displayNodeNumbers_checkBox = QtGui.QCheckBox(self.displayNodes_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeNumbers_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeNumbers_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeNumbers_checkBox.setObjectName("displayNodeNumbers_checkBox")
        self.horizontalLayout_6.addWidget(self.displayNodeNumbers_checkBox)
        self.displayNodeDerivatives_checkBox = QtGui.QCheckBox(self.displayNodes_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivatives_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivatives_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivatives_checkBox.setObjectName("displayNodeDerivatives_checkBox")
        self.horizontalLayout_6.addWidget(self.displayNodeDerivatives_checkBox)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.verticalLayout_9.addWidget(self.displayNodes_frame)
        self.displayNodeDerivativeLabels_frame = QtGui.QFrame(self.displayOptions_groupBox)
        self.displayNodeDerivativeLabels_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayNodeDerivativeLabels_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayNodeDerivativeLabels_frame.setObjectName("displayNodeDerivativeLabels_frame")
        self.horizontalLayout_7 = QtGui.QHBoxLayout(self.displayNodeDerivativeLabels_frame)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.displayNodeDerivativeLabelsD1_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD1_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD1_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD1_checkBox.setObjectName("displayNodeDerivativeLabelsD1_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD1_checkBox)
        self.displayNodeDerivativeLabelsD2_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD2_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD2_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD2_checkBox.setObjectName("displayNodeDerivativeLabelsD2_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD2_checkBox)
        self.displayNodeDerivativeLabelsD3_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD3_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD3_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD3_checkBox.setObjectName("displayNodeDerivativeLabelsD3_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD3_checkBox)
        self.displayNodeDerivativeLabelsD12_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD12_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD12_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD12_checkBox.setObjectName("displayNodeDerivativeLabelsD12_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD12_checkBox)
        self.displayNodeDerivativeLabelsD13_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD13_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD13_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD13_checkBox.setObjectName("displayNodeDerivativeLabelsD13_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD13_checkBox)
        self.displayNodeDerivativeLabelsD23_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD23_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD23_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD23_checkBox.setObjectName("displayNodeDerivativeLabelsD23_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD23_checkBox)
        self.displayNodeDerivativeLabelsD123_checkBox = QtGui.QCheckBox(self.displayNodeDerivativeLabels_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayNodeDerivativeLabelsD123_checkBox.sizePolicy().hasHeightForWidth())
        self.displayNodeDerivativeLabelsD123_checkBox.setSizePolicy(sizePolicy)
        self.displayNodeDerivativeLabelsD123_checkBox.setObjectName("displayNodeDerivativeLabelsD123_checkBox")
        self.horizontalLayout_7.addWidget(self.displayNodeDerivativeLabelsD123_checkBox)
        self.verticalLayout_9.addWidget(self.displayNodeDerivativeLabels_frame)
        self.displayLines_frame = QtGui.QFrame(self.displayOptions_groupBox)
        self.displayLines_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayLines_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayLines_frame.setObjectName("displayLines_frame")
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.displayLines_frame)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.displayLines_checkBox = QtGui.QCheckBox(self.displayLines_frame)
        self.displayLines_checkBox.setObjectName("displayLines_checkBox")
        self.horizontalLayout_5.addWidget(self.displayLines_checkBox)
        self.displayLinesExterior_checkBox = QtGui.QCheckBox(self.displayLines_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayLinesExterior_checkBox.sizePolicy().hasHeightForWidth())
        self.displayLinesExterior_checkBox.setSizePolicy(sizePolicy)
        self.displayLinesExterior_checkBox.setObjectName("displayLinesExterior_checkBox")
        self.horizontalLayout_5.addWidget(self.displayLinesExterior_checkBox)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_9.addWidget(self.displayLines_frame)
        self.displaySurfaces_frame = QtGui.QFrame(self.displayOptions_groupBox)
        self.displaySurfaces_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displaySurfaces_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displaySurfaces_frame.setObjectName("displaySurfaces_frame")
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.displaySurfaces_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.displaySurfaces_checkBox = QtGui.QCheckBox(self.displaySurfaces_frame)
        self.displaySurfaces_checkBox.setObjectName("displaySurfaces_checkBox")
        self.horizontalLayout_3.addWidget(self.displaySurfaces_checkBox)
        self.displaySurfacesExterior_checkBox = QtGui.QCheckBox(self.displaySurfaces_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displaySurfacesExterior_checkBox.sizePolicy().hasHeightForWidth())
        self.displaySurfacesExterior_checkBox.setSizePolicy(sizePolicy)
        self.displaySurfacesExterior_checkBox.setObjectName("displaySurfacesExterior_checkBox")
        self.horizontalLayout_3.addWidget(self.displaySurfacesExterior_checkBox)
        self.displaySurfacesTranslucent_checkBox = QtGui.QCheckBox(self.displaySurfaces_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displaySurfacesTranslucent_checkBox.sizePolicy().hasHeightForWidth())
        self.displaySurfacesTranslucent_checkBox.setSizePolicy(sizePolicy)
        self.displaySurfacesTranslucent_checkBox.setObjectName("displaySurfacesTranslucent_checkBox")
        self.horizontalLayout_3.addWidget(self.displaySurfacesTranslucent_checkBox)
        self.displaySurfacesWireframe_checkBox = QtGui.QCheckBox(self.displaySurfaces_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displaySurfacesWireframe_checkBox.sizePolicy().hasHeightForWidth())
        self.displaySurfacesWireframe_checkBox.setSizePolicy(sizePolicy)
        self.displaySurfacesWireframe_checkBox.setObjectName("displaySurfacesWireframe_checkBox")
        self.horizontalLayout_3.addWidget(self.displaySurfacesWireframe_checkBox)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem4)
        self.verticalLayout_9.addWidget(self.displaySurfaces_frame)
        self.displayElements_frame = QtGui.QFrame(self.displayOptions_groupBox)
        self.displayElements_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayElements_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayElements_frame.setObjectName("displayElements_frame")
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.displayElements_frame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.displayElementNumbers_checkBox = QtGui.QCheckBox(self.displayElements_frame)
        self.displayElementNumbers_checkBox.setObjectName("displayElementNumbers_checkBox")
        self.horizontalLayout_4.addWidget(self.displayElementNumbers_checkBox)
        self.displayElementAxes_checkBox = QtGui.QCheckBox(self.displayElements_frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayElementAxes_checkBox.sizePolicy().hasHeightForWidth())
        self.displayElementAxes_checkBox.setSizePolicy(sizePolicy)
        self.displayElementAxes_checkBox.setObjectName("displayElementAxes_checkBox")
        self.horizontalLayout_4.addWidget(self.displayElementAxes_checkBox)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem5)
        self.verticalLayout_9.addWidget(self.displayElements_frame)
        self.displayMisc_frame = QtGui.QFrame(self.displayOptions_groupBox)
        self.displayMisc_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.displayMisc_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.displayMisc_frame.setObjectName("displayMisc_frame")
        self.horizontalLayout_8 = QtGui.QHBoxLayout(self.displayMisc_frame)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.displayAxes_checkBox = QtGui.QCheckBox(self.displayMisc_frame)
        self.displayAxes_checkBox.setObjectName("displayAxes_checkBox")
        self.horizontalLayout_8.addWidget(self.displayAxes_checkBox)
        self.displayAnnotationPoints_checkBox = QtGui.QCheckBox(self.displayMisc_frame)
        self.displayAnnotationPoints_checkBox.setObjectName("displayAnnotationPoints_checkBox")
        self.horizontalLayout_8.addWidget(self.displayAnnotationPoints_checkBox)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.verticalLayout_9.addWidget(self.displayMisc_frame)
        self.toolBox.addItem(self.Scaffoldpage, "")
        self.alignPage = QtGui.QWidget()
        self.alignPage.setGeometry(QtCore.QRect(0, 0, 340, 856))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignPage.sizePolicy().hasHeightForWidth())
        self.alignPage.setSizePolicy(sizePolicy)
        self.alignPage.setObjectName("alignPage")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.alignPage)
        self.verticalLayout_5.setSpacing(7)
        self.verticalLayout_5.setContentsMargins(0, 3, 0, 3)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.alignSettingsGroupBox = QtGui.QGroupBox(self.alignPage)
        self.alignSettingsGroupBox.setObjectName("alignSettingsGroupBox")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.alignSettingsGroupBox)
        self.verticalLayout_7.setSpacing(3)
        self.verticalLayout_7.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.alignLoadSaveWidgets = QtGui.QWidget(self.alignSettingsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignLoadSaveWidgets.sizePolicy().hasHeightForWidth())
        self.alignLoadSaveWidgets.setSizePolicy(sizePolicy)
        self.alignLoadSaveWidgets.setObjectName("alignLoadSaveWidgets")
        self.gridLayout = QtGui.QGridLayout(self.alignLoadSaveWidgets)
        self.gridLayout.setSpacing(3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.alignAutoCentreButton = QtGui.QPushButton(self.alignLoadSaveWidgets)
        self.alignAutoCentreButton.setObjectName("alignAutoCentreButton")
        self.gridLayout.addWidget(self.alignAutoCentreButton, 0, 0, 1, 1)
        self.alignLoadButton = QtGui.QPushButton(self.alignLoadSaveWidgets)
        self.alignLoadButton.setEnabled(True)
        self.alignLoadButton.setObjectName("alignLoadButton")
        self.gridLayout.addWidget(self.alignLoadButton, 0, 1, 1, 1)
        self.verticalLayout_7.addWidget(self.alignLoadSaveWidgets)
        self.alignScaleWidgets = QtGui.QWidget(self.alignSettingsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.alignScaleWidgets.sizePolicy().hasHeightForWidth())
        self.alignScaleWidgets.setSizePolicy(sizePolicy)
        self.alignScaleWidgets.setObjectName("alignScaleWidgets")
        self.formLayout = QtGui.QFormLayout(self.alignScaleWidgets)
        self.formLayout.setContentsMargins(3, 3, 3, 3)
        self.formLayout.setSpacing(3)
        self.formLayout.setObjectName("formLayout")
        self.alignScaleLabel = QtGui.QLabel(self.alignScaleWidgets)
        self.alignScaleLabel.setObjectName("alignScaleLabel")
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.alignScaleLabel)
        self.alignScaleLineEdit = QtGui.QLineEdit(self.alignScaleWidgets)
        self.alignScaleLineEdit.setObjectName("alignScaleLineEdit")
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.alignScaleLineEdit)
        self.alignRotationLabel = QtGui.QLabel(self.alignScaleWidgets)
        self.alignRotationLabel.setObjectName("alignRotationLabel")
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.alignRotationLabel)
        self.alignRotationLineEdit = QtGui.QLineEdit(self.alignScaleWidgets)
        self.alignRotationLineEdit.setObjectName("alignRotationLineEdit")
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.alignRotationLineEdit)
        self.alignOffsetLabel = QtGui.QLabel(self.alignScaleWidgets)
        self.alignOffsetLabel.setObjectName("alignOffsetLabel")
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.alignOffsetLabel)
        self.alignOffsetLineEdit = QtGui.QLineEdit(self.alignScaleWidgets)
        self.alignOffsetLineEdit.setObjectName("alignOffsetLineEdit")
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.alignOffsetLineEdit)
        self.alignMirrorCheckBox = QtGui.QCheckBox(self.alignScaleWidgets)
        self.alignMirrorCheckBox.setObjectName("alignMirrorCheckBox")
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.alignMirrorCheckBox)
        self.alignSaveButton = QtGui.QPushButton(self.alignScaleWidgets)
        self.alignSaveButton.setEnabled(True)
        self.alignSaveButton.setObjectName("alignSaveButton")
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.alignSaveButton)
        self.verticalLayout_7.addWidget(self.alignScaleWidgets)
        self.verticalLayout_5.addWidget(self.alignSettingsGroupBox)
        self.alignResetButton = QtGui.QPushButton(self.alignPage)
        self.alignResetButton.setObjectName("alignResetButton")
        self.verticalLayout_5.addWidget(self.alignResetButton)
        spacerItem7 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem7)
        self.toolBox.addItem(self.alignPage, "")
        self.fitPage = QtGui.QWidget()
        self.fitPage.setGeometry(QtCore.QRect(0, 0, 340, 856))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitPage.sizePolicy().hasHeightForWidth())
        self.fitPage.setSizePolicy(sizePolicy)
        self.fitPage.setObjectName("fitPage")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.fitPage)
        self.verticalLayout_4.setSpacing(7)
        self.verticalLayout_4.setContentsMargins(0, 3, 0, 3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBoxProjectData = QtGui.QGroupBox(self.fitPage)
        self.groupBoxProjectData.setObjectName("groupBoxProjectData")
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBoxProjectData)
        self.gridLayout_4.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.projectPointsButton = QtGui.QPushButton(self.groupBoxProjectData)
        self.projectPointsButton.setObjectName("projectPointsButton")
        self.gridLayout_4.addWidget(self.projectPointsButton, 0, 0, 1, 1)
        self.projectClearButton = QtGui.QPushButton(self.groupBoxProjectData)
        self.projectClearButton.setObjectName("projectClearButton")
        self.gridLayout_4.addWidget(self.projectClearButton, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBoxProjectData)
        self.filterDataGroupBox = QtGui.QGroupBox(self.fitPage)
        self.filterDataGroupBox.setObjectName("filterDataGroupBox")
        self.gridLayout_3 = QtGui.QGridLayout(self.filterDataGroupBox)
        self.gridLayout_3.setSpacing(3)
        self.gridLayout_3.setContentsMargins(3, 3, 3, 3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.filterTopErrorProportionLineEdit = QtGui.QLineEdit(self.filterDataGroupBox)
        self.filterTopErrorProportionLineEdit.setObjectName("filterTopErrorProportionLineEdit")
        self.gridLayout_3.addWidget(self.filterTopErrorProportionLineEdit, 0, 2, 1, 1)
        self.filterNonNormalPushButton = QtGui.QPushButton(self.filterDataGroupBox)
        self.filterNonNormalPushButton.setObjectName("filterNonNormalPushButton")
        self.gridLayout_3.addWidget(self.filterNonNormalPushButton, 2, 0, 1, 1)
        self.filterNonNormalProjectionLimitLabel = QtGui.QLabel(self.filterDataGroupBox)
        self.filterNonNormalProjectionLimitLabel.setObjectName("filterNonNormalProjectionLimitLabel")
        self.gridLayout_3.addWidget(self.filterNonNormalProjectionLimitLabel, 2, 1, 1, 1)
        self.filterNonNormalProjectionLimitLineEdit = QtGui.QLineEdit(self.filterDataGroupBox)
        self.filterNonNormalProjectionLimitLineEdit.setObjectName("filterNonNormalProjectionLimitLineEdit")
        self.gridLayout_3.addWidget(self.filterNonNormalProjectionLimitLineEdit, 2, 2, 1, 1)
        self.filterTopErrorPushButton = QtGui.QPushButton(self.filterDataGroupBox)
        self.filterTopErrorPushButton.setObjectName("filterTopErrorPushButton")
        self.gridLayout_3.addWidget(self.filterTopErrorPushButton, 0, 0, 1, 1)
        self.filterTopErrorProportionLabel = QtGui.QLabel(self.filterDataGroupBox)
        self.filterTopErrorProportionLabel.setObjectName("filterTopErrorProportionLabel")
        self.gridLayout_3.addWidget(self.filterTopErrorProportionLabel, 0, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.filterDataGroupBox)
        self.fitSettingsGroupBox = QtGui.QGroupBox(self.fitPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitSettingsGroupBox.sizePolicy().hasHeightForWidth())
        self.fitSettingsGroupBox.setSizePolicy(sizePolicy)
        self.fitSettingsGroupBox.setObjectName("fitSettingsGroupBox")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.fitSettingsGroupBox)
        self.verticalLayout_6.setSpacing(3)
        self.verticalLayout_6.setContentsMargins(3, 3, 3, 3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.fitSettingsLoadSaveWidgets = QtGui.QWidget(self.fitSettingsGroupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fitSettingsLoadSaveWidgets.sizePolicy().hasHeightForWidth())
        self.fitSettingsLoadSaveWidgets.setSizePolicy(sizePolicy)
        self.fitSettingsLoadSaveWidgets.setObjectName("fitSettingsLoadSaveWidgets")
        self.gridLayout_2 = QtGui.QGridLayout(self.fitSettingsLoadSaveWidgets)
        self.gridLayout_2.setSpacing(3)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.fitLoadButton = QtGui.QPushButton(self.fitSettingsLoadSaveWidgets)
        self.fitLoadButton.setEnabled(True)
        self.fitLoadButton.setObjectName("fitLoadButton")
        self.gridLayout_2.addWidget(self.fitLoadButton, 0, 0, 1, 1)
        self.fitSaveButton = QtGui.QPushButton(self.fitSettingsLoadSaveWidgets)
        self.fitSaveButton.setEnabled(True)
        self.fitSaveButton.setObjectName("fitSaveButton")
        self.gridLayout_2.addWidget(self.fitSaveButton, 0, 1, 1, 1)
        self.gridLayout_2.setRowStretch(0, 2)
        self.verticalLayout_6.addWidget(self.fitSettingsLoadSaveWidgets)
        self.fitSettingsWidget = QtGui.QWidget(self.fitSettingsGroupBox)
        self.fitSettingsWidget.setObjectName("fitSettingsWidget")
        self.formLayout_2 = QtGui.QFormLayout(self.fitSettingsWidget)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setContentsMargins(0, 3, 0, 3)
        self.formLayout_2.setVerticalSpacing(3)
        self.formLayout_2.setObjectName("formLayout_2")
        self.fitStrainPenaltyLabel = QtGui.QLabel(self.fitSettingsWidget)
        self.fitStrainPenaltyLabel.setObjectName("fitStrainPenaltyLabel")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.fitStrainPenaltyLabel)
        self.fitStrainPenaltyLineEdit = QtGui.QLineEdit(self.fitSettingsWidget)
        self.fitStrainPenaltyLineEdit.setObjectName("fitStrainPenaltyLineEdit")
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.fitStrainPenaltyLineEdit)
        self.fitPerformButton = QtGui.QPushButton(self.fitSettingsWidget)
        self.fitPerformButton.setObjectName("fitPerformButton")
        self.formLayout_2.setWidget(5, QtGui.QFormLayout.SpanningRole, self.fitPerformButton)
        self.fitMaxIterationsLabel = QtGui.QLabel(self.fitSettingsWidget)
        self.fitMaxIterationsLabel.setObjectName("fitMaxIterationsLabel")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.fitMaxIterationsLabel)
        self.fitEdgeDiscontinuityPenaltyLabel = QtGui.QLabel(self.fitSettingsWidget)
        self.fitEdgeDiscontinuityPenaltyLabel.setObjectName("fitEdgeDiscontinuityPenaltyLabel")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.fitEdgeDiscontinuityPenaltyLabel)
        self.fitEdgeDiscontinuityPenaltyLineEdit = QtGui.QLineEdit(self.fitSettingsWidget)
        self.fitEdgeDiscontinuityPenaltyLineEdit.setObjectName("fitEdgeDiscontinuityPenaltyLineEdit")
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.fitEdgeDiscontinuityPenaltyLineEdit)
        self.fitMaxIterationsSpinBox = QtGui.QSpinBox(self.fitSettingsWidget)
        self.fitMaxIterationsSpinBox.setMinimum(1)
        self.fitMaxIterationsSpinBox.setMaximum(100)
        self.fitMaxIterationsSpinBox.setProperty("value", 1)
        self.fitMaxIterationsSpinBox.setObjectName("fitMaxIterationsSpinBox")
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.fitMaxIterationsSpinBox)
        self.verticalLayout_6.addWidget(self.fitSettingsWidget)
        self.verticalLayout_4.addWidget(self.fitSettingsGroupBox)
        spacerItem8 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem8)
        self.toolBox.addItem(self.fitPage, "")
        self.verticalLayout_3.addWidget(self.toolBox)
        self.frame = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(3, 3, 3, 3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.viewAllButton = QtGui.QPushButton(self.frame)
        self.viewAllButton.setObjectName("viewAllButton")
        self.horizontalLayout_2.addWidget(self.viewAllButton)
        self.doneButton = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.doneButton.sizePolicy().hasHeightForWidth())
        self.doneButton.setSizePolicy(sizePolicy)
        self.doneButton.setObjectName("doneButton")
        self.horizontalLayout_2.addWidget(self.doneButton)
        self.verticalLayout_3.addWidget(self.frame)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_2.addWidget(self.scrollArea)
        self.dock_widget.setWidget(self.dockWidgetContents)
        self.horizontalLayout.addWidget(self.dock_widget)
        self.sceneviewerWidget = BaseSceneviewerWidget(ScaffoldfitterWidget, shared_open_gl_widget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sceneviewerWidget.sizePolicy().hasHeightForWidth())
        self.sceneviewerWidget.setSizePolicy(sizePolicy)
        self.sceneviewerWidget.setObjectName("sceneviewerWidget")
        self.horizontalLayout.addWidget(self.sceneviewerWidget)

        self.retranslateUi(ScaffoldfitterWidget)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(6)
        QtCore.QMetaObject.connectSlotsByName(ScaffoldfitterWidget)

    def retranslateUi(self, ScaffoldfitterWidget):
        ScaffoldfitterWidget.setWindowTitle(QtGui.QApplication.translate("ScaffoldfitterWidget", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.dock_widget.setWindowTitle(QtGui.QApplication.translate("ScaffoldfitterWidget", "Fitting Steps", None, QtGui.QApplication.UnicodeUTF8))
        self.meshType_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Mesh type:", None, QtGui.QApplication.UnicodeUTF8))
        self.parameterSet_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Parameter set:", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteElementRanges_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Delete element ID ranges (e.g. 1,2-5,13):", None, QtGui.QApplication.UnicodeUTF8))
        self.scale_label.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Scale x*y*z:", None, QtGui.QApplication.UnicodeUTF8))
        self.displayOptions_groupBox.setTitle(QtGui.QApplication.translate("ScaffoldfitterWidget", "Display options:", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodePoints_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Node points", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeNumbers_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Node numbers", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivatives_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Node derivatives", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD1_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "D1", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD2_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "D2", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD3_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "D3", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD12_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "D12", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD13_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "D13", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD23_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "D23", None, QtGui.QApplication.UnicodeUTF8))
        self.displayNodeDerivativeLabelsD123_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "D123", None, QtGui.QApplication.UnicodeUTF8))
        self.displayLines_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Lines", None, QtGui.QApplication.UnicodeUTF8))
        self.displayLinesExterior_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Exterior", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySurfaces_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Surfaces", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySurfacesExterior_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Exterior", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySurfacesTranslucent_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Transluc.", None, QtGui.QApplication.UnicodeUTF8))
        self.displaySurfacesWireframe_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Wireframe", None, QtGui.QApplication.UnicodeUTF8))
        self.displayElementNumbers_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Element numbers", None, QtGui.QApplication.UnicodeUTF8))
        self.displayElementAxes_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Element axes", None, QtGui.QApplication.UnicodeUTF8))
        self.displayAxes_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Axes", None, QtGui.QApplication.UnicodeUTF8))
        self.displayAnnotationPoints_checkBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Annotation points", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.Scaffoldpage), QtGui.QApplication.translate("ScaffoldfitterWidget", "Scaffold Parametrs", None, QtGui.QApplication.UnicodeUTF8))
        self.alignSettingsGroupBox.setTitle(QtGui.QApplication.translate("ScaffoldfitterWidget", "Alignment", None, QtGui.QApplication.UnicodeUTF8))
        self.alignAutoCentreButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Offset the model to the centre of the data points. May need to click View All afterwards.", None, QtGui.QApplication.UnicodeUTF8))
        self.alignAutoCentreButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Align Scaffold To Data", None, QtGui.QApplication.UnicodeUTF8))
        self.alignLoadButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Load pre-saved alignment settings", None, QtGui.QApplication.UnicodeUTF8))
        self.alignLoadButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Load Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.alignScaleLabel.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Scale:", None, QtGui.QApplication.UnicodeUTF8))
        self.alignScaleLineEdit.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Scaling of model, where 1.0 is original size", None, QtGui.QApplication.UnicodeUTF8))
        self.alignRotationLabel.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Rotation:", None, QtGui.QApplication.UnicodeUTF8))
        self.alignRotationLineEdit.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Rotation of the model as 3 Euler angles", None, QtGui.QApplication.UnicodeUTF8))
        self.alignOffsetLabel.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Offset:", None, QtGui.QApplication.UnicodeUTF8))
        self.alignOffsetLineEdit.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Offset of the model in x, y ,z", None, QtGui.QApplication.UnicodeUTF8))
        self.alignMirrorCheckBox.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Mirror", None, QtGui.QApplication.UnicodeUTF8))
        self.alignSaveButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Save alignment settings for recall later or when next run", None, QtGui.QApplication.UnicodeUTF8))
        self.alignSaveButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Save Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.alignResetButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Reset the alignment settings", None, QtGui.QApplication.UnicodeUTF8))
        self.alignResetButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.alignPage), QtGui.QApplication.translate("ScaffoldfitterWidget", "Initial Rigid Alignment", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBoxProjectData.setTitle(QtGui.QApplication.translate("ScaffoldfitterWidget", "1. Projections", None, QtGui.QApplication.UnicodeUTF8))
        self.projectPointsButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Project or re-project all active points to the nearest locations on the model surfaces", None, QtGui.QApplication.UnicodeUTF8))
        self.projectPointsButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Project Points", None, QtGui.QApplication.UnicodeUTF8))
        self.projectClearButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Clear all projections and reset the active data points to include all", None, QtGui.QApplication.UnicodeUTF8))
        self.projectClearButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Reset", None, QtGui.QApplication.UnicodeUTF8))
        self.filterDataGroupBox.setTitle(QtGui.QApplication.translate("ScaffoldfitterWidget", "2. Filter data", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTopErrorProportionLineEdit.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Proportion of maximum error (0.0 to 1.0) used to filter data points", None, QtGui.QApplication.UnicodeUTF8))
        self.filterNonNormalPushButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Remove data points with projections whose dot product with the surface normal is less than the given limit (1.0 is perface alignment, 0.0 is orthogonal)", None, QtGui.QApplication.UnicodeUTF8))
        self.filterNonNormalPushButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Remove non-normal", None, QtGui.QApplication.UnicodeUTF8))
        self.filterNonNormalProjectionLimitLabel.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Proj. Limit:", None, QtGui.QApplication.UnicodeUTF8))
        self.filterNonNormalProjectionLimitLineEdit.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Minimum dot product for removing non-normal projections (<=1.0 where 1.0 is perfecly normal)", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTopErrorPushButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Remove data points with errors greater than the given proportion of the maximum error", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTopErrorPushButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Remove top error", None, QtGui.QApplication.UnicodeUTF8))
        self.filterTopErrorProportionLabel.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Proportion:", None, QtGui.QApplication.UnicodeUTF8))
        self.fitSettingsGroupBox.setTitle(QtGui.QApplication.translate("ScaffoldfitterWidget", "3. Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.fitLoadButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Load pre-saved fitting settings", None, QtGui.QApplication.UnicodeUTF8))
        self.fitLoadButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Load Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.fitSaveButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Save fit settings for recall later or when next run", None, QtGui.QApplication.UnicodeUTF8))
        self.fitSaveButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Save Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.fitStrainPenaltyLabel.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Strain Penalty:", None, QtGui.QApplication.UnicodeUTF8))
        self.fitStrainPenaltyLineEdit.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Penalty factor for strains, typically << 1.0 e.g. 0.001", None, QtGui.QApplication.UnicodeUTF8))
        self.fitPerformButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Perform fitting up to at most the set number of iteratations", None, QtGui.QApplication.UnicodeUTF8))
        self.fitPerformButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Perform Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.fitMaxIterationsLabel.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Max. Iterations:", None, QtGui.QApplication.UnicodeUTF8))
        self.fitEdgeDiscontinuityPenaltyLabel.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Edge Discontinuity Pen.:", None, QtGui.QApplication.UnicodeUTF8))
        self.fitEdgeDiscontinuityPenaltyLineEdit.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Penalty factor for discontinuity between adjacent elements. Used only with non-C1 continuous coordinate fields", None, QtGui.QApplication.UnicodeUTF8))
        self.fitMaxIterationsSpinBox.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Maximum number of iterations to limit fit time if convergence is slow", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBox.setItemText(self.toolBox.indexOf(self.fitPage), QtGui.QApplication.translate("ScaffoldfitterWidget", "Smooth Fitting", None, QtGui.QApplication.UnicodeUTF8))
        self.viewAllButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Adjust the view to see the whole model", None, QtGui.QApplication.UnicodeUTF8))
        self.viewAllButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "View All", None, QtGui.QApplication.UnicodeUTF8))
        self.doneButton.setToolTip(QtGui.QApplication.translate("ScaffoldfitterWidget", "Finish this step", None, QtGui.QApplication.UnicodeUTF8))
        self.doneButton.setText(QtGui.QApplication.translate("ScaffoldfitterWidget", "Done", None, QtGui.QApplication.UnicodeUTF8))

from opencmiss.zincwidgets.basesceneviewerwidget import BaseSceneviewerWidget
